set -g mouse on
set -g history-limit 100000
set -g base-index 1
setw -g pane-base-index 1

set -g status-interval 5
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#S"
set -g status-right "%Y-%m-%d %H:%M"

bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"
